version: '3.8'
services:
  theos:
    build:
      context: .
    volumes:
      - ./theos:/home/me/theos
      - ./sdks:/home/me/theos/sdks
      - work:/home/me/work
    privileged: true
    network_mode: host
    container_name: theos
    stdin_open: true
    tty: true
volumes:
  work:
